version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.3.1

jobs:
  setup:
    executor: continuation/default
    parameters:
      repo:
        type: string
      branch:
        type: string
    steps:
      - checkout
      - run:
          name: Generate config
          command: |
            .circleci/generate-config.sh ${GH_BOT_PAT} << parameters.repo >> << parameters.branch >>
      - continuation/continue:
          configuration_path: .circleci/continue-config.yml

workflows:
  tests:
    jobs:
      - setup:
          context:
            - TOKENS
            - slack-secrets
          matrix:
            parameters:
              repo: ["bedrock-trellis-ds"]
              branch: ["php7.4", "develop"]
      - setup:
          context:
            - TOKENS
            - slack-secrets
          matrix:
            parameters:
              repo: ["emergences"]
              branch: ["develop"]
