version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.3.1

jobs:
  continue:
    executor: continuation/default
    parameters:
      repo:
        type: string
      branch:
        type: string
    steps:
      - checkout
      - run: |
          curl --header "Authorization: token ${GH_BOT_PAT}" \
            --header 'Accept: application/vnd.github.v3.raw' \
            --output /tmp/main.yml \
            --location https://raw.githubusercontent.com/digital-swing/<< parameters.repo >>/<< parameters.branch >>/trellis/group_vars/all/main.yml
          echo "export PHP_VERSION=\"$(cat /tmp/main.yml | grep php_version | cut -d'"' -f 2)\"" >> $BASH_ENV
      - run: |
          echo '{ \"repo\" : \"<< parameters.repo >>\" , \"branch\" : \"<< parameters.branch >>\" , \"php-version\" : \"${PHP_VERSION}" }'
      - continuation/continue:
          configuration_path: .circleci/continue-config.yml
          parameters: '{ \"repo\" : \"<< parameters.repo >>\" , \"branch\" : \"<< parameters.branch >>\" , \"php-version\" : \"${PHP_VERSION}" }'

workflows:
  tests:
    jobs:
      - continue:
          matrix:
            parameters:
              repo: ["bedrock-trellis-ds"]
              branch: ["php7.4", "develop"]
      - continue:
          matrix:
            parameters:
              repo: ["emergences"]
              branch: ["develop"]
