#!/bin/bash 
set -o pipefail

declare -A ansible_vars
ansible_vars[site-name]="ansible develop -i hosts/develop -m shell -c local -a \"echo {{ (wordpress_sites | first) }}\" | tail -1"
ansible_vars[theme-name]="ansible develop -i hosts/develop -m shell -c local -a \"echo {{ theme }}\" | tail -1"
ansible_vars[src-dir]="ansible develop -i hosts/develop -m shell -c local -a \"echo {{ theme_dist_folder }}\" | tail -1"
ansible_vars[production_flag]="ansible develop -i hosts/develop -m shell -c local -e item=\"{{ (wordpress_sites | dict2items | first ) }}\" -a \"echo {{ (npm_build_folders | first).production_flag }}\" | tail -1"

for key in "${!ansible_vars[@]}"
    do echo "export ${key}='$(eval "${ansible_vars[$key]}")'" >> "$BASH_ENV"
done